### ISSUE TITLE
[Question/Feedback]: Proposal to modify the default behavior in Tags Interface Spec

### ISSUE THREAD

**Issue by jchancellor-ms** [Azure/Azure-Verified-Modules#122]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

It is common to inherit tags from a parent resource group and or from a parent resource.  Proposal for feedback is to modify the Tags spec to allow for the option to inherit and append tags for child resources in addition to the current option of only inserting the child resource tags.  

This should help minimize errors from replaying some existing tags.

**Comment by jtracey93** [comment]
Current thinking is that we can provide a code snippet on how to achieve this instead of adding as a feature to the modules/tags, which reduces the need for another API call to do a GET and e.g. using a data resource/existing resource.

@matt-FFFFFF to create a snippet and place it in the AVM docs wherever suitable

**Comment by mbilalamjad** [comment]
@matt-FFFFFF appreciate an update on this

**Comment by matt-FFFFFF** [comment]
I don't think it should be required to implement tag inheritance and merging. We can provide examples of how to do so but I still believe this should be done outside the module.

**Comment by mbilalamjad** [comment]
@jchancellor-ms based on @matt-FFFFFF response above, we'll close this one for now, lets us know offline if you think otherwise and it needs more discussion
