### ISSUE TITLE
[Module Proposal]: `avm/res/app/container-app`

### ISSUE THREAD

**Issue by oZakari** [Azure/Azure-Verified-Modules#128]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals

### Check this module doesn't already exist in another project that is being evolved into AVM

- [X] I have checked for that this module doesn't already exist in CARML or TFVM

### Terraform or Bicep?

Bicep

### Module Classification?

Resource Module

### Module Name

avm/res/app/container-app

### Module Details

Not proposing a new module but interested in taking ownership of existing CARML module.

For reference: https://github.com/Azure/ResourceModules/tree/main/modules/app/container-app

### Do you want to be the owner of this module?

Yes

### Module Owner's GitHub Username

oZakari

**Comment by matebarabas** [comment]
@oZakari, thanks for opening this request and volunteering! I'll shortly send you a request to officially confirm ownership. 

Also, @prjelesi is going to reach out to you separately and help with the next steps, given this is a migrate from CARML scenario. 

Thank you!

**Comment by matebarabas** [comment]
Hi @oZakari,

Thanks for requesting/proposing to be an AVM module owner.

We just want to confirm you agree to the below pages that define what module ownership means:

- https://azure.github.io/Azure-Verified-Modules/specs/shared/team-definitions
- https://azure.github.io/Azure-Verified-Modules/specs/shared
- https://azure.github.io/Azure-Verified-Modules/help-support/module-support

Any questions or clarifications needed, let us know.

If you agree please just reply to this issue with the exact sentence below (as this helps with our automation 👍):

"I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"

Thanks,

The AVM Core Team

**Comment by oZakari** [comment]
I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER

**Comment by matebarabas** [comment]
Reopening. 

@oZakari, please note that this issue can only be closed when the module is developed, tested, and published in the Bicep public registry.

**Comment by matebarabas** [comment]
Hi @oZakari,

Thanks for confirming that you wish to own this AVM module and understand the related requirements and responsibilities.

We just want to ask you to double check a few important things before you start the development.

Please visit the [module index](https://azure.github.io/Azure-Verified-Modules/indexes/) page of your module and use the following values explicitly as provided there:

- `ModuleName`
- `TelemetryIdPrefix`
- `ModuleOwnersGHTeam` and `ModuleContributorsGHTeam`
- Repository name and folder path defined in `RepoURL`

You can now start the development of this module! Happy coding! 🎉

Please respond to this comment, once your module is ready to be published!

Any further questions or clarifications needed, let us know.

Thanks,

The AVM Core Team

**Comment by kewalaka** [comment]
semantics perhaps - but would **avm-res-container-app** be a better choice?  There is avm-res-container-registry, and presumably there will need to be one for managed environments (avm-res-container-environment ?)

seems more logical to me to place the container items closer together alphabetically

If the intent is to group various app options together, then I think the appservice repository name needs reconsideration?

**Comment by oZakari** [comment]
Hi @kewalaka, I referenced the (spec)[https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-rmnfr1---category-naming---module-naming]. I think this was done to try to reduce the number of dashes for resource names with lots of spaces and to try to keep it as consistent as possible with the resource schema itself. For container registry it should be avm-res-containerregistry-registry instead of avm-res-container-registry.

@matebarabas Just taking a quick look at other resource module names, looks like module for Action Group has a hypen, but it shouldn't either based upon the schema unless I am missing something.

**Comment by matebarabas** [comment]
@ozakari, @kewalaka,

Please see the naming convention for [resource](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-rmnfr1---category-naming---module-naming) and [pattern](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-pmnfr1---category-naming---module-naming) modules under the respective shared requirement.

- The explanation in the previous comment is correct. The right name for the Container Registry module is `avm-res-containerregistry-registry`
- The correct name for the Container App module is: `avm-res-app-containerapp`. --> The information in this issue is correct.
- The correct name for the Action Group module is `avm-res-insights-actiongroup`. --> The name information in this issue (#207) was incorrectly captured and it remained unnoticed. The module was published with the correct name. Please note that the issue for this module was captured retrospectively as an exception, since the module was already being worked on by an AVM core team member before the process for managing the issues (including issue templates, automation, documentation, etc.) was put in place. For good recordkeeping, the core team was asked to make sure they cover all modules that were migrated from CARML with "module proposal" issues. I've corrected the mistake. Thank you for calling this out!

**Comment by matebarabas** [comment]
@oZakari,

Due to a recent change in the naming convention for AVM Bicep modules, this module is getting an updated name.

The title and description of this GH issue has been updated to reflect the name change. **Please make sure you adhere to the new naming convention when publishing your module!** 

Please see the new naming convention in:
- [RMNFR1](https://azure.github.io/Azure-Verified-Modules/specs/shared/#bicep-resource-module-naming) for resource modules
- [PMNFR1](https://azure.github.io/Azure-Verified-Modules/specs/shared/#bicep-pattern-module-naming) for pattern modules

Please note that the Telemetry ID and name of GitHub Teams haven't changed.

If you feel uncertain about any details, please check the [Bicep modules indexes](https://azure.github.io/Azure-Verified-Modules/indexes/bicep/).

**Comment by oZakari** [comment]
https://github.com/oZakari/bicep-registry-modules/tree/container-apps

**Comment by matebarabas** [comment]
Thanks for the update @oZakari! Please let us know once you've submitted a PR (by providing a link to it). Thank you in advance!

**Comment by matebarabas** [comment]
Hi @oZakari, Happy New Year! I hope you had a great holiday season and had a chance to recharge! 😊

I just would like to check back on this issue and ask how far do you think you are? Can you please share your expected timeline on publishing this module? 

Thank you!

CC: @jeanchg

**Comment by oZakari** [comment]
Hi @matebarabas, nearly complete, pushing to get the PR out by this Friday.

**Comment by oZakari** [comment]
[PR](https://github.com/Azure/bicep-registry-modules/pull/833)

**Comment by matebarabas** [comment]
- [x] Module published. PR: https://github.com/Azure/bicep-registry-modules/pull/833
- [x] GitHub teams are available and assigned to their parents.
- [x] `CODEOWNERS` file updated.
 
Thank you for your work @oZakari! I'm closing this issue now.
