### ISSUE TITLE
[Module Proposal]: `avm/res/desktop-virtualization/application-group`

### ISSUE THREAD

**Issue by moisesjgomez** [Azure/Azure-Verified-Modules#146]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals

### Check this module doesn't already exist in another project that is being evolved into AVM

- [X] I have checked for that this module doesn't already exist in CARML or TFVM

### Terraform or Bicep?

Bicep

### Module Classification?

Resource Module

### Module Name

avm/res/desktop-virtualization/application-group

### Module Details

We will be migrating and modifying the CARML module we are using for AVD LZA.

Please add as the following co-owner:
@danycontre 

cc: @matebarabas as we discussed submitting the issues.

### Do you want to be the owner of this module?

Yes

### Module Owner's GitHub Username

moisesjgomez

**Comment by matebarabas** [comment]
Hi @moisesjgomez,

Thanks for requesting/proposing to be an AVM module owner.

We just want to confirm you agree to the below pages that define what module ownership means:

- https://azure.github.io/Azure-Verified-Modules/specs/shared/team-definitions
- https://azure.github.io/Azure-Verified-Modules/specs/shared
- https://azure.github.io/Azure-Verified-Modules/help-support/module-support

Any questions or clarifications needed let us know.

If you agree please just reply to this issue with the exact sentence below (as this helps with our automation 👍):

"I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"

Thanks

The AVM Core Team

**Comment by moisesjgomez** [comment]
I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER 

cc: @danycontre

**Comment by matebarabas** [comment]
@moisesjgomez, @danycontre, 

Due to a recent change in the naming convention for AVM Bicep modules, this module is getting an updated name.

The title and description of this GH issue has been updated to reflect the name change. **Please make sure you adhere to the new naming convention when publishing your module!** 

Please see the new naming convention in:
- [RMNFR1](https://azure.github.io/Azure-Verified-Modules/specs/shared/#bicep-resource-module-naming) for resource modules
- [PMNFR1](https://azure.github.io/Azure-Verified-Modules/specs/shared/#bicep-pattern-module-naming) for pattern modules

Please note that the Telemetry ID and name of GitHub Teams haven't changed.

If you feel uncertain about any details, please check the [Bicep modules indexes](https://azure.github.io/Azure-Verified-Modules/indexes/bicep/).

**Comment by moisesjgomez** [comment]
This module is in active development, aiming to complete by end of next week.

**Comment by moisesjgomez** [comment]
https://github.com/Azure/bicep-registry-modules/pull/832

**Comment by matebarabas** [comment]
- [x] Module published.
- [x] GitHub teams are available and assigned to their parents.
- [x] `CODEOWNERS` file updated.
 
Thank you for your work @moisesjgomez! I'm closing this issue now.
