### ISSUE TITLE
[Question/Feedback]:

### ISSUE THREAD

**Issue by autocloudarc** [Azure/Azure-Verified-Modules#1513]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Description

Is it likely that this project would consider including OpenTofu (ref: https://opentofu.org/) modules as well?

**Comment by pichuang** [comment]
Just to add that. I think the overall concept of AVM is good, but we have customers who are stuck on `Terraform v1.5.7` due to Terraform's license issue, which should be a bit of an obstacle to the implementation of AVM, if there is support for OpenTofu, it would be very helpful.


[7. What products will be covered by BSL 1.1 in their next release?](https://www.hashicorp.com/license-faq#products-covered-by-bsl)

**Comment by matebarabas** [comment]
Please see AVM's statement on OpenTofu, here: https://github.com/Azure/Azure-Verified-Modules/discussions/1512
Related issue: https://github.com/Azure/Azure-Verified-Modules/issues/825
