### ISSUE TITLE
[Module Proposal]: `avm-res-storage-storageaccount`

### ISSUE THREAD

**Issue by chinthakaru** [Azure/Azure-Verified-Modules#35]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals

### Terraform or Bicep?

Terraform

### Module Classification?

Resource Module

### Module Name

Module name - avm-res-storage-storageaccount
Github Repo name - terraform-azurerm-avm-res-storage-storageaccount

### Module Details

Terraform Storage account module for multiple SA requirements.

### Do you want to be the owner of this module?

Yes

### Module Owner's GitHub Username

chinthakaru

**Comment by lonegunmanb** [comment]
https://github.com/lonegunmanb/terraform-azure-storage-account
Still WIP

**Comment by matt-FFFFFF** [comment]
@chinthakaru will fork the module started by @lonegunmanb - as he now has other priorities

**Comment by lonegunmanb** [comment]
Now you can access [new repo](https://github.com/Azure/terraform-azurerm-avm-res-storage-storageaccounts) as maintainer @chinthakaru, the repo is yours.

**Comment by jtracey93** [comment]
Thanks @lonegunmanb for this. 

JFYI we don't close the issues until the module is released, so I have reoppened.

**Comment by PmeshramPM** [comment]
@chinthakaru - please pay attention to Module name description. I have updated that based on specs.

**Comment by kewalaka** [comment]
as per [this issue](https://github.com/Azure/terraform-azurerm-avm-res-storage-storageaccount/issues/13), the AVM guidance (https://azure.github.io/Azure-Verified-Modules/contributing/terraform/#template-repository) recommends using the [AVM template](https://github.com/Azure/terraform-azurerm-avm-template).

Currently the storage account resource module is cloned from the terraform verified modules template (TFVM).

Please would someone comment on the process for alignment (i.e. does the repo need to be re-created or will PRs to align with AVM be accepted?)

**Comment by PmeshramPM** [comment]
@kewalaka - If I understand your question correctly, This is basically evolving the TFVM storage account module so that it align to AVM specs. The repo is recreated with AVM naming conventions, template, guidance and alignment with specs and then PRs into the new repo.

**Comment by kewalaka** [comment]
@PmeshramPM - correct this came from TFVM.  At the top of the repository just under the title it says:

```generated from https://github.com/Azure/terraform-verified-module```

Whereas AVM modules should say:

```generated from https://github.com/Azure/terraform-azurerm-avm-template```

Using the AVM template means that GitHub Actions and general layout & things like "shared components" (e.g. implementations of private endpoints/locks) are aligned.

One option is to re-create this repo from the correct template (I think that's better)

The other options is to submit PRs to align this repo, cloned from the wrong template, to align (that's valid too).

Hope that clarifies 🙂

**Comment by kewalaka** [comment]
> @PmeshramPM - correct this came from TFVM. At the top of the repository just under the title it says:
> 
> `generated from https://github.com/Azure/terraform-verified-module`
> 
> Whereas AVM modules should say:
> 
> `generated from https://github.com/Azure/terraform-azurerm-avm-template`
> 
> Using the AVM template means that GitHub Actions and general layout & things like "shared components" (e.g. implementations of private endpoints/locks) are aligned.
> 
> One option is to re-create this repo from the correct template (I think that's better)
> 
> The other options is to submit PRs to align this repo, cloned from the wrong template, to align (that's valid too).
> 
> Hope that clarifies 🙂

Hi @Azure/avm-core-team-technical @PmeshramPM - it is possible to get some feedback on this last statement, please?  i.e. does the storage account repo need to be re-created from the correct github template?

**Comment by mbilalamjad** [comment]
@kewalaka thanks for the feedback

I believe a new repo would have to be created using the AVM template

tagging @matt-FFFFFF to confirm

@chinthakaru please let us know if you have done so already

CC: @PmeshramPM

**Comment by kewalaka** [comment]
ok cool.  I've got a little present for you all - based on the initial work from @lonegunmanb i've refactored things into an AVM style here (clone off the right template):

https://github.com/kewalaka/terraform-azurerm-avm-res-storage-storageaccount

it's still work in progress, the AVM interfaces are implemented but I'm expecting issues with the private endpoint.  Some basic E2E tests are passing though (default settings + a storage acc + container with access keys disabled), my plan is to re-introduce the complete example once I've got a bit more confidence.

private endpoints is the bit I need for my project, so that's where my attention will be next - if anyone wants to help whilst the new home is sorted out, PRs are welcome.

@chinthakaru  let me know when the new place is available and i'll raise a PR.

**Comment by davidkarlsen** [comment]
Yay - any ca timeframe on when this will become an official Azure/AVM module - if it is close I can wait, else we need to roll our own in the mean time.

**Comment by kewalaka** [comment]
> Yay - any ca timeframe on when this will become an official Azure/AVM module - if it is close I can wait, else we need to roll our own in the mean time.

hi @davidkarlsen - this is the opinion of an enthusiastic contributor not a MSFT'er.  My understanding is these won't be supported until they get to v1... however all is not lost!  The guidance I give my customers is when writing new modules (or updating existing ones), to align them "in the style of AVM" - along with the crucial examples & patterns that sit on top (as that's how you drive usage & business value).

Then, when they become official, you will be able to swap out the modules written for the official ones from Microsoft. 

In my view, there's value in getting your intermediate+ Terraformers writing these, because inevitably there will need to be fixes, people need to get used to working with them, and your team will probably learn a few good practices and techniques along the way (I have!).  It also makes it easier to switch between Bicep and Terraform if the styles are similar (as is the intent), e.g. the way role assignments follow the same pattern between resources (& their children).

The other challenges I see with seasoned Terraformers is they are prone to looking inside the module and freaking out over the "complexity", I've seen this a lot in the Bicep world with CARML - I can't put the answer any better than this FAQ: https://azure.github.io/Azure-Verified-Modules/faq/#arent-avm-resource-modules-too-complex-for-people-less-skilled-in-iac-technologies.  I'm highlighting, you may need to do some "convincing" to get teams on board.

In the meantime, the world will keep turning, and things need to get done.  If you'd like to contribute fixes or help to the repo I list above, great, knowing there's no support behind it, but my intent is to fold behind the official resource and deprecate mine as soon as it is available.  Again noting, if we do this right, it'll be a drop in replacement.

**Comment by stemaMSFT** [comment]
@jtracey93 @lonegunmanb is this work being dropped? Just asking about the status of this issue

**Comment by kewalaka** [comment]
> @jtracey93 @lonegunmanb is this work being dropped? Just asking about the status of this issue

just clarifying my key ask for the AVM team is whether the repo has to be re-created as it has been cloned from the TFVM template not the AVM template (ref questions on 22nd Oct & 2nd Nov above).

then.. once answered.. I'll know if I should PR in my "AVM alignment" work (ref comment on 18th Nov), or wait for a new repo.

much appreciated @stemaMSFT

**Comment by chinthakaru** [comment]
@kewalaka  Thanks for opening up the issue. This repo reviewing internally with AVM standards and will be available within the next few weeks after the internal review.  

cc @stemaMSFT @lonegunmanb @jtracey93

**Comment by kewalaka** [comment]
I'm afraid the last comment doesn't make sense to me.   I've raised this directly with a couple MSFT'ers, and remain a little concerned that the current repository has somehow made it to a published state without it following AVM standards.

https://github.com/azure/terraform-azurerm-avm-res-storage-storageaccount

Functionally, it is great (as one would expect, from the work of the amazing @lonegunmanb), but as [this PR illustrates](https://github.com/Azure/terraform-azurerm-avm-res-storage-storageaccount/pull/23), it is quite a distance from being "AVM aligned".

So, I politely ask for clarity on two points;

- the repository being reviewed - is this a new internal as-yet-unpublished version?
- may I please have an answer regarding whether a repo *must* be created from the AVM template?

thanks again - sorry for being fussy - I just want to get this module on the right path asap, noting it has been up since July with very few commits, and people are raising issues & thus likely starting to build on it.

Since we seem to be going around the blocks with this, i'm going to broadly cc:
@chinthakaru, @jtracey93, @matt-FFFFFF, @mbilalamjad

**Comment by PmeshramPM** [comment]
@kewalaka - I followed up with @chinthakaru.  Please see the answer to your questions 

1. the repository being reviewed - is this a new internal as-yet-unpublished version?
     Yes, this is unpublished version as of yet @chinthakaru is working on it. 

2. may I please have an answer regarding whether a repo must be created from the AVM template?
     since this was migration from TFVM repo, we originally used that template but now we have aligned the content with AVM template.

**Comment by kewalaka** [comment]
great, so i've raised this clarification to the documentation: https://github.com/Azure/Azure-Verified-Modules/pull/429

Expecting this answer, I PR'ed my changes that i initially shared back on 18th Nov against the existing repo yesterday: https://github.com/Azure/terraform-azurerm-avm-res-storage-storageaccount/pull/23

I've put my work out on display, and answered community questions from @davidkarlsen - can we please collectively do the same, so the community has visibility & we can help contribute. 

@PmeshramPM and @chinthakaru - this has personally been a frustrating exercise to date (and I know being on the receiving end of me nagging is not pleasant too 😄).

As an example of being more open, can **we get this alignment process made public as a PR on the existing repo**, please - or - join in with [my PR](https://github.com/Azure/terraform-azurerm-avm-res-storage-storageaccount/pull/23)?  I can understand the internal review prior to the repo being published, but not after.

many thanks & regards!

**Comment by kewalaka** [comment]
summarising feedback from @matt-FFFFFF - the AVM template should be used for future repos, we don't want to modify the guidance as per my previous suggestion, but will work with exceptions such as storage without requiring that this repo is re-created (hope that's a fair summary 😊)

the [avm-sa branch on the storage account repo](https://github.com/Azure/terraform-azurerm-avm-res-storage-storageaccount/tree/avm-sa) is tracking the change for AVM alignment, I've re-worked the PR I last mentioned in [this new PR](https://github.com/Azure/terraform-azurerm-avm-res-storage-storageaccount/pull/26), noting my PR, whilst incomplete, brings this a lot closer to AVM specs.

**Comment by matt-FFFFFF** [comment]
We now also have repository governance tooling to help track and update important files in repos.

**Comment by chinthakaru** [comment]
Initial review has been completed and we are working on a few latest changes to the module.

**Comment by mbilalamjad** [comment]
Thank you so much @chinthakaru for your contribution

Closing as module has been published to terraform registry below
https://registry.terraform.io/modules/Azure/avm-res-storage-storageaccount/azurerm/latest

Further discussion on this module including issues & PRs to take please on its repo below
https://github.com/Azure/terraform-azurerm-avm-res-storage-storageaccount
