### ISSUE TITLE
[Module Proposal]: `avm/res/insights/scheduled-query-rule`

### ISSUE THREAD

**Issue by krbar** [Azure/Azure-Verified-Modules#376]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes; or I'm proposing the module to be migrated from CARML/TFVM.

### Bicep or Terraform?

Bicep

### Module Classification?

Resource Module

### Module Name

avm/res/insights/scheduled-query-rule

### Module Details

Scheduled Query Rule module, migration from CARML

### Do you want to be the owner of this module?

No

**Comment by matebarabas** [comment]
This module will be migrated from CARML by @krbar without an owner. If you'd like to volunteer to be the module owner, please indicate it in a comment! Thanks!

**Comment by krbar** [comment]
@matebarabas Module has been merged into the BRM repo: https://github.com/Azure/bicep-registry-modules/pull/712

**Comment by matebarabas** [comment]
- [x] Module published.
- [x] GitHub teams are available and assigned to their parents.
- [x] `CODEOWNERS` file updated.
 
Thank you for your work @krbar! I'm closing this issue now.

Since this module was migrated from CARML without an owner, an orphaned module request was also created: https://github.com/Azure/Azure-Verified-Modules/issues/411
