### ISSUE TITLE
[Module Proposal]: `avm/res/insights/webtest`

### ISSUE THREAD

**Issue by krbar** [Azure/Azure-Verified-Modules#406]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes; or I'm proposing the module to be migrated from CARML/TFVM.

### Bicep or Terraform?

Bicep

### Module Classification?

Resource Module

### Module Name

avm/res/insights/webtest

### Module Details

Migration from CARML

### Do you want to be the owner of this module?

No

**Comment by matebarabas** [comment]
@krbar, just double checking: do you mean to migrate this one from CARML (without becoming the owner)? Thanks!

**Comment by krbar** [comment]
> @krbar, just double checking: do you mean to migrate this one from CARML (without becoming the owner)? Thanks!

Correct

**Comment by krbar** [comment]
@matebarabas PR in review: https://github.com/Azure/bicep-registry-modules/pull/728

**Comment by matebarabas** [comment]
- [x] PR merged; Module published.
- [x] GitHub teams are available and assigned to their parents.
- [x] `CODEOWNERS` file updated.
 
Thank you for your work @krbar! I'm closing this issue now.

Since this module was migrated from CARML without an owner, an orphaned module request was also created: https://github.com/Azure/Azure-Verified-Modules/issues/433
