### ISSUE TITLE
[Module Proposal]: avm-res-network-expressroutegateway (tf)

### ISSUE THREAD

**Issue by khushal08** [Azure/Azure-Verified-Modules#421]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes; or I'm proposing the module to be migrated from CARML/TFVM.

### Bicep or Terraform?

Terraform

### Module Classification?

Resource Module

### Module Name

avm-res-network-expressroutegateway

### Module Details

Terraform module for Azure expressroute gateway. 
To connect Azure virtual network to the on-premises network using ExpressRoute circuit, a virtual network gateway is required. A virtual network gateway serves two purposes: exchange IP routes between the networks and route network traffic. 
This type of gateway is also referred to as an ExpressRoute gateway.

### Do you want to be the owner of this module?

Yes

### Module Owner's GitHub Username (handle)

khushal08

**Comment by mbilalamjad** [comment]
Hi @khushal08, thank you for submitting the module proposal, express route gateway is already covered by the below pattern module, please feel free to review, use and provide feedback on that module in case there are any gaps or issues. Since this module does already exist therefore, I will proceed to close this. Feel free to reach out offline and in case you feel we need to reopen it.
https://github.com/Azure/Azure-Verified-Modules/issues/157
