### ISSUE TITLE
[Module Proposal]: `avm/res/data-protection/backup-vault`

### ISSUE THREAD

**Issue by segraef** [Azure/Azure-Verified-Modules#461]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes; or I'm proposing the module to be migrated from CARML/TFVM.

### Bicep or Terraform?

Bicep

### Module Classification?

Resource Module

### Module Name

avm/res/data-protection/backup-vault

### Module Details

carml > avm

### Do you want to be the owner of this module?

No

**Comment by matebarabas** [comment]
@segraef will migrate this module from CARML, without becoming its owner. The module will be marked as orphaned once the migration is complete, unless someone volunteers to own it.

**If someone wishes to become the owner of this module, please indicate your intent in a comment on this issue.**

**Comment by matebarabas** [comment]
PR: https://github.com/Azure/bicep-registry-modules/pull/742

**Comment by matebarabas** [comment]
- [x] PR merged; Module published.
- [x] GitHub teams are available and assigned to their parents.
- [x] `CODEOWNERS` file updated.
 
Thank you for your work @segraef! I'm closing this issue now.

Since this module was migrated from CARML without an owner, an orphaned module request was also created: https://github.com/Azure/Azure-Verified-Modules/issues/540
