### ISSUE TITLE
[Module Proposal]: `avm/res/network/firewall-policy`

### ISSUE THREAD

**Issue by krbar** [Azure/Azure-Verified-Modules#488]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes; or I'm proposing the module to be migrated from CARML/TFVM.

### Bicep or Terraform?

Bicep

### Module Classification?

Resource Module

### Module Name

avm/res/network/firewall-policy

### Module Details

Firewall Policy module, migration from CARML

### Do you want to be the owner of this module?

No

**Comment by krbar** [comment]
@matebarabas I'm happy to migrate this module, without owning it.

**Comment by matebarabas** [comment]
Thank you @krbar! Feel free to get started! ;)

**Comment by matebarabas** [comment]
- [x] PR merged; Module published. PR: https://github.com/Azure/bicep-registry-modules/pull/767
- [x] GitHub teams are available and assigned to their parents.
- [x] `CODEOWNERS` file updated.
 
Thank you for your work @krbar! I'm closing this issue now.

Since this module was migrated from CARML without an owner, an orphaned module request was also created: https://github.com/Azure/Azure-Verified-Modules/issues/501
