### ISSUE TITLE
[Question/Feedback]: Module-support creation child resources (Bicep)

### ISSUE THREAD

**Issue by dewolfs** [Azure/Azure-Verified-Modules#578]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

I've used the Bicep CARML modules in the past for creating child resources like a secret in a already existing key-vault and a route in a existing routeTable.

I was using the secret child resource of the key-vault CARML module as follows:
`module vaults './modules/key-vault/vault/secret/main.bicep' = {...}`

I've tried to use the same method with AVM but this does not work.
Auto-complete error msg is telling me this resource(secret) does not exist.

Similar to the key-vault resource, I've tried to add a new network route into an existing routeTable using the Bicep code below, the result is that
1. Existing routes get deleted, scary!! (Open issue since 2016: https://github.com/Azure/azure-quickstart-templates/issues/2786)
2. The route listed in the code below gets created.

```
resource ref_existingRTHub 'Microsoft.Network/routeTables@2023-05-01' existing = {
  name: route1
  scope: resourceGroup(rgSecurity)
}

module route 'br/public:avm/res/network/route-table:0.2.1' = {
  scope: resourceGroup(rgSecurity)
  name: 'test'
  params: {
    name: ref_existingRTHub.name
    routes: [
      {
        name: 'routex'
        properties: {
          nextHopType: 'VirtualAppliance'
          addressPrefix: '1.1.1.0/24'
          nextHopIpAddress: '1.1.1.1'
        }
      }
    ]
  }
}
```

- Is there a way to create these 2 child-resource today using AVM?
- If not, will it be possible with AVM in the future?

**Comment by matebarabas** [comment]
@Azure/avm-core-team-technical-bicep, can you please help with this issue?

**Comment by AlexanderSehr** [comment]
Hey @dewolfs,
Thanks for opening this issue - it's a fact of which we're very much aware. Let me provide you with the short & long for it:

Short answer:
- As per the way the Public Registry is implemented today, it was not possible to publish child-modules separate from its parents
- As such, you cannot reference e.g. a `avm/res/key-vault/vault/key` module directly from the registry, but can only deploy it through its parent `avm/res/key-vault/vault` - UNLESS you actually grab the module folder locally as we opted to retain the structure, we established in CARML
- However, we kept the door open to make this possible in the future if there is a demand and figure out how to make it possible

Long answer:
- The Public Registry versions & publishes only top-level modules. Amongst other things the reason is that modules must be pre-registered upon first publishing first & the CI would need to be able to recursively version & publish modules in the same way the CARML CI did.
- This is something we have on our radar since we started migrating the modules, but opted to get the library migration done first, and then expand upon that basis. As you can imagine, too many moving parts are a breeding ground for problems 👀 
- That being said, the CARML CI will continue to exist, and we'll see to ensure it is fully compatible with AVM. Today it is to an extent, but some changes are still required and I'm working on keeping the features as aligned as possible. Once the migration is done, I can focus on it fully. However, you could essentially take the modules in the `avm/res` folder and throw them into CARML's `modules` folder and it should almost work as is. Some Pester tests may need updating, and you'd need to add a `version.json` file to the child modules as well as a telemetry parameter to each child's interface. Once done, it should pretty much operate as before. 


> **Note:** There is one inherent danger with what you described above with the VNET and I want to elaborate a bit on the issue you linked. Some modules (especially in the Network namespace like RouteTable, NSG, VNET, VPN-Gateway, etc.) also have their child-modules (e.g. subnet for vnet) as a property. You may notice, that our module implementation in those cases appears a bit odd on our part as we essentially deploy each child twice (first via the property, then directly via the child-module). The reason is that those module will remove the child-resources if they're not deployed via the property - yet the property does not offer the same set of features as the dedicated child-resource. Does that sound cryptic? I bet it does, so let me provide an example:
>- Imagine you deploy the VNET using the raw resource (i.e., `resource vnet 'Microsoft.Network/virtualNetworks@(...)`) without specifying the optional subnets property. This deployment will work like a charm without issue
>- Now imagine you add a subnet either in the portal, or by deploying a subnet resource via the corresponding ARM endpoint (i.e.,  `resource vnet 'Microsoft.Network/virtualNetworks/subnets@(...)`. Again, either will work like a charm
>- This is where it gets problematic. If you now were to deploy the original vnet deployment again without changing anything, the deployment will go ahead and DELETE the subnet you created after. Why? Well, because you did not provide it using the `subnets` property. It's essentially running a 'complete' deployment on the resource as opposed to the 'incremental' module - but this is **by design**. 
>- You can observe this behavior also for the other previously mentioned Network resources - and I only know it from the Network namespace. This has nothing to do with the publishing issue, but given you mentioned that you're deploying routes via the child module I thought you should know. Be careful not to re-deploy the RouteTable itself or you're in for some fun.
