### ISSUE TITLE
[Module Proposal]: `avm-ptn-private-link-dns-zones`

### ISSUE THREAD

**Issue by matt-FFFFFF** [Azure/Azure-Verified-Modules#613]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes; or I'm proposing the module to be migrated from CARML/TFVM.

### Bicep or Terraform?

Terraform

### Module Classification?

Pattern Module

### Module Name

avm-ptn-private-link-dns-zones

### Module Details

Create all private DNS zones needed for private link

Link to supplied vnets

Take in a location param to support things like azure backup

### Do you want to be the owner of this module?

Yes

### Module Owner's GitHub Username (handle)

matt-FFFFFF

**Comment by matt-FFFFFF** [comment]
I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"

**Comment by matt-FFFFFF** [comment]
I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER

**Comment by mbilalamjad** [comment]
Hi @matt-FFFFFF,

Thanks for confirming that you wish to own this AVM module and understand the related requirements and responsibilities!

Before starting development, please ensure ALL the following requirements are met.

**Please use the following values explicitly as provided in the [module index](https://azure.github.io/Azure-Verified-Modules/indexes/) page**:

- For your module:
  - `ModuleName` - for naming your module
  - `TelemetryIdPrefix` - for your module's [telemetry](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-sfr3---category-telemetry---deploymentusage-telemetry)
- For your module's repository:
  - Repo name and folder path are defined in `RepoURL`
  - Create GitHub teams for module owners and contributors and grant them permissions as outlined [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr20---category-contributionsupport---github-teams-only).
  - Grant permissions for the AVM core team and PG teams on your GitHub repo as described [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr9---category-contributionsupport---avm--pg-teams-github-repo-permissions).

Check if this module exists in the other IaC language. If so, collaborate with the other owner for consistency. 👍

You can now start the development of this module! ✅ Happy coding! 🎉

**Please respond to this comment and request a review from the AVM core team once your module is ready to be published! Please include a link pointing to your PR, once available. 🙏**

Any further questions or clarifications needed, let us know!

Thanks,

The AVM Core Team

**Comment by jtracey93** [comment]
@PmeshramPM im going to take this one from @matt-FFFFFF to help out and spread the load. Can you do the triage process etc. and update the CSV, cheers 👍

**Comment by jtracey93** [comment]
I would like to request a review of my module. The latest code is in a PR titled AVM-Review-PR on the module repo and all checks on that PR are passing. https://github.com/Azure/terraform-azurerm-avm-ptn-network-private-link-private-dns-zones/pull/6

The terraform linting checks that are failing are expected due to:

1. Failures for the `terraform_naming_convention` is expected as I kept the naming for the locals in snake case but wanted to keep the `regionCode` or `regionName` string as one, the same as it is declared in all the replacement logic in the module to make it easier for debugging and future contributions
2. The Error of `Error: module owners MUST output the `resource_id` in their modules (required_output_rmfr7)` is not applicable to pattern modules
3. The Error of `Error: module owners MUST output the `resource` in their modules (required_output_tffr2)` is being removed as i understand it as a spec requirement and also would be very large for this module.

I have tried to exclude these after speaking with @matt-FFFFFF yesterday in the file of [`.tflint.override.hcl`](https://github.com/Azure/terraform-azurerm-avm-ptn-network-private-link-private-dns-zones/pull/6/files#diff-aff2d2c31535385c0db65e294fe1187c45b5ea9686b82398105a4adfd37d82cf) but it doesnt seem to be working 😢 

So its good for a review based on this

@Azure/avm-core-team-technical-terraform

**Comment by mbilalamjad** [comment]
Thank you @jtracey93 for requesting a review of your module. The AVM module review process has been initiated, please perform the **Requested Actions** on the [AVM-Review issue](https://github.com/Azure/terraform-azurerm-avm-ptn-network-private-link-private-dns-zones/issues/12) on the module repo.

**Comment by jtracey93** [comment]
> Thank you @jtracey93 for requesting a review of your module. The AVM module review process has been initiated, please perform the **Requested Actions** on the [AVM-Review issue](https://github.com/Azure/terraform-azurerm-avm-ptn-network-private-link-private-dns-zones/issues/12) on the module repo.

These are done @mbilalamjad

**Comment by jtracey93** [comment]
The initial review of this module is complete and the module has been published to the registry. Requesting AVM team to close this module proposal and mark the module available in the module index.
