### ISSUE TITLE
[Module Proposal]: `avm/res/service-networking/traffic-controller`

### ISSUE THREAD

**Issue by shailwx** [Azure/Azure-Verified-Modules#712]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes; or I'm proposing the module to be migrated from CARML/TFVM.

### Bicep or Terraform?

Bicep

### Module Classification?

Resource Module

### Module Name

avm/res/service-networking/traffic-controller

### Module Details

A bicep module for application gateway for containers

### Do you want to be the owner of this module?

Yes

### Module Owner's GitHub Username (handle)

shailwx

**Comment by matebarabas** [comment]
@shailwx, thank you for proposing this module! In line with @mbilalamjad's comments on the [sister issue](https://github.com/Azure/Azure-Verified-Modules/issues/711), I'd like to ask the following questions:

- This module seems already in development - [`avm/res/network/application-gateway`](https://github.com/Azure/Azure-Verified-Modules/issues/258). Could you please have a look and confirm if this is what you intended to propose?
- In case you believe your use case is different, can you please elaborate on your requirements? Please note that in case another module (whether resource or pattern module) needs to be developed, we'll need to find a Microsoft FTE to own the module, since this is a requirement for AVM. As your GitHub handle doesn't seem to be assigned with a Microsoft corporate account, I'm assuming you're not an FTE. In case you are one, you can link your account here: https://aka.ms/LinkYourGitHubAccount (this works for FTEs only).

**Comment by shailwx** [comment]
Hi @matebarabas,

- Application Gateway and Application Gateway for containers are two different products from same family of load balancing products. 
- No I am not a Microsoft FTE.

**Comment by matebarabas** [comment]
@shailwx, apologies for the confusion and thanks for the clarification!

I can see that in case of this resource, we're talking about the following resource provider and resource type `Microsoft.ServiceNetworking/trafficControllers`. According to this, I've updated the issue's name and description to `avm/res/service-networking/traffic-controller`. 

This module would also need to cater for the child resources of this parent resource:
- `Microsoft.ServiceNetworking/trafficControllers/Frontends`
- `Microsoft.ServiceNetworking/trafficControllers/Associations`

Please note that:
- the Bicep/ARM template reference doesn't seem to be available for this service just yet,
- the API reference for the `2023-05-01-preview` (only this **preview version** is available) can be accessed here: [TrafficController - Create Or Update](https://learn.microsoft.com/en-us/rest/api/applicationgatewaycontainers/traffic-controller/create-or-update?view=rest-applicationgatewaycontainers-2023-05-01-preview&tabs=HTTP),
- based on the AVM requirement documented in [SFR1](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-sfr1--- category-composition---preview-services), certain restrictions apply when the service is in preview or only has a preview API available.

Please allow some time for the AVM core team (@Azure/avm-core-team-technical-bicep) to thoroughly assess this situation with this proposal. Thank you for your patience!

Thanks for confirming you're not a Microsoft FTE! If/when this proposal gets admitted, we will try to find a module owner you can work with as a contributor. We highly appreciate your help!

CC: @mbilalamjad

**Comment by matebarabas** [comment]
@shailwx, thank you for your patience! **The AVM Core Team has triaged this proposal and approved it for development as a resource module.** 

The next step is to identify a Microsoft FTE, who could be the module owner. Since you originally indicated you'd like to own this module (which unfortunately is not possible today, as only FTEs can be owners), I'm assuming you'd like to actively contribute to the development, testing, publication and perhaps maintenance of this module. Is my assumption correct?

I also would like to ask if by any chance you know and/or have worked with any of our existing [AVM module owners](https://azure.github.io/Azure-Verified-Modules/indexes/bicep/bicep-resource-modules/#available-modules). I'm only asking this, as if this was the case, we'd continue by asking that person, if they'd be interested in working with you as an external contributor.
If you don't know any of the existing AVM module owners, there's still no need to worry, as we'll try to identify someone who could work with you. For time zone level proximity, could you please confirm that you're working based out of CET?

Thank you!

**Comment by shailwx** [comment]
@matebarabas,
Thanks for the update. Thanks for accepting the proposal for the development of the module

Yes, I would like to actively contribute to the development, testing, publication and perhaps maintenance of this module.
No, I am not worked with any AVM module owners so far. And yes I am based in CET.

Thank you so much :)

**Comment by krbar** [comment]
@matebarabas @shailwx  Hello, I'm happy to be the admin owner and help with the dev and publication process for this module.

**Comment by matebarabas** [comment]
Thank you @krbar! I'll share the contact details of @shailwx with you internally, so you can set up a call with him. Until then, let's do a quick handshake on this issue!

**Comment by matebarabas** [comment]
Hi @krbar,

Thanks for confirming that you wish to own this AVM module and understand the related requirements and responsibilities!

Before starting development, please ensure ALL the following requirements are met.

**Please use the following values explicitly as provided in the [module index](https://azure.github.io/Azure-Verified-Modules/indexes/) page**:

- For your module:
  - `ModuleName` - for naming your module
  - `TelemetryIdPrefix` - for your module's [telemetry](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-sfr3---category-telemetry---deploymentusage-telemetry)
- For your module's repository:
  - Repo name and folder path are defined in `RepoURL`
  - Create GitHub teams for module owners and contributors and grant them permissions as outlined [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr20---category-contributionsupport---github-teams-only).
  - Grant permissions for the AVM core team and PG teams on your GitHub repo as described [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr9---category-contributionsupport---avm--pg-teams-github-repo-permissions).

Check if this module exists in the other IaC language. If so, collaborate with the other owner for consistency. 👍

You can now start the development of this module! ✅ Happy coding! 🎉

**Please respond to this comment and request a review from the AVM core team once your module is ready to be published! Please include a link pointing to your PR, once available. 🙏**

Any further questions or clarifications needed, let us know!

Thanks,

The AVM Core Team

**Comment by krbar** [comment]
FYI: I reached internally someone from Azure Docs team and reported the missing template reference for `Microsoft.ServiceNetworking/trafficControllers`. He will add it to the backlog so I hope that we will have a documentation soon.

**Comment by shailwx** [comment]
Hi, @matebarabas 
Me and Kris have started working on this. We need some help from PG as we are missing some documentation on the APIs. 
We will resume our as soon as we get some feedback from PG

**Comment by krbar** [comment]
@shailwx The template reference for this module is now available. See https://learn.microsoft.com/en-us/azure/templates/microsoft.servicenetworking/trafficcontrollers?pivots=deployment-language-bicep

**Comment by krbar** [comment]
@shailwx any updates on the module creation progress?

**Comment by matebarabas** [comment]
> @shailwx any updates on the module creation progress?

@shailwx, did you manage to start the development of this module? Do you need any sort of help? Thanks!

**Comment by shailwx** [comment]
@krbar, I will need your help on this. Can we schedule a call for this ?

**Comment by krbar** [comment]
> @krbar, I will need your help on this. Can we schedule a call for this ?

Meeting invite sent

**Comment by krbar** [comment]
@matebarabas Module has been published: https://github.com/Azure/bicep-registry-modules/pull/3169

**Comment by matebarabas** [comment]
- [x] Module published.
- [x] GitHub teams are available and assigned to their parents.
- [x] `CODEOWNERS` file updated.
- [x] Issue template file updated.
 
Thank you for your work @krbar! I'm closing this issue now.
