### ISSUE TITLE
[Module Proposal]: `avm-res-dbforpostgresql-flexibleserver`

### ISSUE THREAD

**Issue by Menghua1** [Azure/Azure-Verified-Modules#714]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes; or I'm proposing the module to be migrated from CARML/TFVM.

### Bicep or Terraform?

Terraform

### Module Classification?

Resource Module

### Module Name

avm-res-dbforpostgresql-flexibleserver

### Module Details

Requested by the AZD team: https://github.com/Azure/Azure-Verified-Modules/issues/261
Needs module owner.
CC: @jongio

### Do you want to be the owner of this module?

No

**Comment by mbilalamjad** [comment]
Hi @Menghua1 thank you for the module proposal, as requesting in the template, kindly check before opening a module proposal if there's one that already exists, since there is a proposal for [avm-res-dbforpostgresql-flexibleserver](https://github.com/Azure/Azure-Verified-Modules/issues/273) already therefore will close this proposal. You are welcome to comment on the original proposal and contribute over there.
