### ISSUE TITLE
[Question/Feedback]: Diagnostic Settings Interface missing retention policy

### ISSUE THREAD

**Issue by jachin84** [Azure/Azure-Verified-Modules#909]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

I noticed when configuring some diagnostic settings on a resource that the `diagnosticSettingType` is missing the `retentionPolicy` on both logs and metrics. See https://learn.microsoft.com/en-us/azure/templates/microsoft.insights/diagnosticsettings?pivots=deployment-language-bicep#retentionpolicy. 

I'm looking through the interface for Diagnostic Settings at https://azure.github.io/Azure-Verified-Modules/specs/shared/interfaces/#diagnostic-settings and it's not included in the standard interface. Was there a deliberate choice to not include the retention policy or did it slip through the cracks? 

I image this would be simple to add:
```bicep
...
  logCategoriesAndGroups: {
    @description('Optional. Name of a Diagnostic Log category for a resource type this setting is applied to. Set the specific logs to collect here.')
    category: string?

    @description('Optional. Name of a Diagnostic Log category group for a resource type this setting is applied to. Set to `allLogs` to collect all logs.')
    categoryGroup: string?

    @description('Optional. Enable or disable the category explicitly. Default is `true`.')
    enabled: bool?

    @description('Optional. The retention policy for the diagnostic logs when using a Storage Account.')
    retentionPolicy: {
      @description('Optional. The number of days to keep the diagnostic logs. Set to `0` to keep logs indefinitely.')
      days: int
      
      @description('Optional. Enable or disable the retention policy explicitly. Default is `true`.')
      enabled: bool?
    }?
  }[]?

  @description('Optional. The name of metrics that will be streamed. "allMetrics" includes all possible metrics for the resource. Set to `[]` to disable metric collection.')
  metricCategories: {
    @description('Required. Name of a Diagnostic Metric category for a resource type this setting is applied to. Set to `AllMetrics` to collect all metrics.')
    category: string

    @description('Optional. Enable or disable the category explicitly. Default is `true`.')
    enabled: bool?

    @description('Optional. The retention policy for the metrics when using a Storage Account.')
    retentionPolicy: {
      @description('Optional. The number of days to keep the diagnostic logs. Set to `0` to keep logs indefinitely.')
      days: int
      
      @description('Optional. Enable or disable the retention policy explicitly. Default is `true`.')
      enabled: bool?
    }?
  }[]?
```

**Comment by matebarabas** [comment]
@Azure/avm-core-team-technical-bicep, @Azure/avm-core-team-technical-terraform, can you please both take a look a look at this request? Thanks!

**Comment by AlexanderSehr** [comment]
Hey @jachin84 & @matebarabas,
this was raised before e.g. here: https://github.com/Azure/bicep-registry-modules/issues/1292

And comes down to the issue mentioned e.g. here
-  https://github.com/Azure/bicep-registry-modules/issues/519
- https://github.com/Azure/ResourceModules/issues/3572

To quote myself in those issues, please take a look at this article in the Microsoft docs where the 'solution' is described: https://learn.microsoft.com/en-us/azure/azure-monitor/essentials/migrate-to-azure-storage-lifecycle-policy?tabs=templates

But long story short - the `retentionPolicy` property on DiagnosticSettings was deprecated in favor of LifecyclePolicies on the targeted Storage Account. I can't say I know why, but that's why the interface looks the way it does.

I know this may not be the answer you've been hoping for, but it's the best I got. If it does however settle the ask, please go ahead and close the issue as not planned. If not, let's keep the conversation going in this thread 😉
