### ISSUE TITLE
[Feedback]: Module naming policy for modules that use multiple Azure provider

### ISSUE THREAD

**Issue by lonegunmanb** [Azure/Azure-Verified-Modules#92]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

[ID: RMNFR1 - Category: Naming - Module Naming](https://github.com/Azure/Azure-Verified-Modules/blob/060bab728a8b0f04666b66cd593051b2c691d811/docs/content/specs/shared/_index.md?plain=1#L767-L768) describes:

>- `<provider>` is the logical abstraction of various APIs used by Terraform. In most cases, this is going to be `azurerm` or `azuread` for resource modules.

Sometimes we might need to use multiple Azure provider in one module, `azurerm` for resource, `azuread` as data source to read service application id, `azapi` to do some operation that `azurerm` do not support.

We might consider removing provider from the module's name.

**Comment by jtracey93** [comment]
Hey @lonegunmanb,

Today AVM is only focussed on Azure, as per https://azure.github.io/Azure-Verified-Modules/faq/#doeswill-avm-cover-microsoft-365-azure-devops-github-etc and raised from #71 

However, Resource Modules as per the [classifications](https://azure.github.io/Azure-Verified-Modules/specs/shared/module-classifications/) only deploy a single primary resource and therefore this requirement today is correct, until we look to add other "clouds" support as per #71 and the FAQ above.

Pattern modules don't have to follow this naming standard as they deploy multiple resources by their nature today.

Finally, the `<provider>` has to be in the module name as per the [HashiCorp publishing requirements](https://developer.hashicorp.com/terraform/registry/modules/publish#requirements) so that it is listed under the correct provider in the registry and hence we are using `azurerm` as its the main provider that most modules will use today.

Hope that helps clarify, let us know if not or we can close 👍

**Comment by jtracey93** [comment]
Reopening due to oof
