### ISSUE TITLE
[Module Proposal]: `avm/res/app/job`

### ISSUE THREAD

**Issue by AlexanderSehr** [Azure/Azure-Verified-Modules#935]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes.

### Bicep or Terraform?

Bicep

### Module Classification?

Resource Module

### Module Name

avm/res/app/job

### Module Details

Migration from [CARML](https://github.com/Azure/ResourceModules/tree/main/modules/app/job).

### Do you want to be the owner of this module?

No

**Comment by AlexanderSehr** [comment]
> **@AlexanderSehr, thanks for submitting this module proposal!**
> 
> Important
> 
> The AVM core team will review it and will try to find a module owner.
> 
> Note
> 
> This message was posted as per [ITA18](https://azure.github.io/Azure-Verified-Modules/help-support/issue-triage/issue-triage-automation/#ita18).

Good luck!

**Comment by matebarabas** [comment]
PR: https://github.com/Azure/bicep-registry-modules/pull/1823

**Comment by matebarabas** [comment]
- [x] Module published.
- [x] GitHub teams are available and assigned to their parents.
- [x] `CODEOWNERS` file updated.
 
Thank you for your work @AlexanderSehr! I'm closing this issue now.

Since this module was migrated from CARML without an owner, an orphaned module request was also created: https://github.com/Azure/Azure-Verified-Modules/issues/955
