### ISSUE TITLE
Defender for Cloud

### ISSUE THREAD

**Issue by gsuttie** [Azure/Azure-Verified-Modules#953]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

Do we know when there might be a defender for cloud avm module available?

**Comment by matebarabas** [comment]
Hi @gsuttie, thank you for submitting this question! 

Please note that as the Defender for Cloud service is called Security Center at the ARM/API level, we have this module published under this name, here: https://github.com/Azure/bicep-registry-modules/tree/main/avm/ptn/security/security-center 

I'm closing this issue now, since the requested module is already available, but please feel free to open a module issue ([here](https://aka.ms/AVM/Bicep/ModuleIssue)) if this module is lacking any features you need. Thank you!
